### ISSUE TITLE
FullCalendar API를 사용해 의사의 달력 화면 INSERT, UPDATE, DELETE 기능 API 구현

### ISSUE THREAD

**Issue by jaekim3220** [jaekim3220/backEndProject#14]
# TODO
- [x] FullCalendar에 추가한 일정을 DB에 INSERT
  - [x] FullCalendar의 `customButtons` 기능과 Modal 창을 사용해 일정을 생성 후 DB에 INSERT
- [x] DB에 있는 일정을 SELECT해서 FullCalendar에 보여줌
  - [x] 의사의 `vacations` 테이블
    - [x] FullCalendar의 `events: function` 기능을 사용해 DB에서 INSERT한 데이터를 바로 화면에 보여줌
  - [x] 환자의 `veservers` 테이블 
- [x] 달력에 표시한 일정을 수정할 수 있는 기능을 추가
  - [x] 수정할 일정(event)를 클릭해서 일정을 업데이트(Update용 Modal 생성)

**Comment by jaekim3220** [comment]
# Uncaught TypeError: Cannot read properties of undefined (reading 'message')
!!!!! Uncaught TypeError: Cannot read properties of undefined (reading 'message') 에러 해결 할것 !!!!! :: DB에서 SELECT 한 데이터를 JSON 형태로 보내서 FullCalendar에서 사용할 수 있는 형태로 가공할 것

# ★★★★★ @Controller와 @RestController의 차이점 이해
- 근본적인 차이점
  - @Controller의 역할은 Model 객체를 만들어 데이터를 담고 View를 찾는 것
  - @Controller와 @ResponseBody를 사용해 JSON 데이터를 전송할 수 있지만 이때 Model 사용이 불가
  - @RestController는 단순히 객체만을 반환하고 객체 데이터는 JSON 또는 XML 형식으로 HTTP 응답에 담아서 전송
- Spring은 @Controller와 @ResponseBody의 동작을 조합한 @RestController을 도입


| 특징 | @Controller | @RestController |
| -- | -- | -- | 
|주요 목적 | HTML 응답 (뷰 렌더링) | 데이터 응답 (JSON, XML 등) |
|뷰 렌더링 | 지원 (ViewResolver 사용) | 미지원 |
|데이터 반환 | @ResponseBody로 명시적 선언 필요 | 기본적으로 데이터 반환 (JSON 등) |
|주요 사용 사례 | 웹 애플리케이션의 페이지 구성 | RESTful API 개발 |
|ViewResolver 지원 여부 | O | X |

```
<Response 방법 - 서버 기준>
@Controller + return String => ViewResolver => HTML 파일 렌더링(Model) => HTML
@Controller + @ResponseBody return String => HTTPMessageConverter => HTML
@Controller + @ResponseBody return 객체(map, list) => HTTPMessageConverter => jackson => JSON
@RestController return map => JSON
Model은 HTML로 이동할 경우 사용(@ResponseBody일 경우 Model 사용 불가)
```
즉, JSON 데이터 전송이 불가능한 Controller 영역에서 FullCalendar에 필요한 event를 JSON 데이터로 변경해서 보내겠다고 **삽질**을 하고 있었던 것. 제발 공부하면 암기만 하지 말고 현장에서 적용하자.

# ★★★★★ stream을 사용해 DB에서 받아온 데이터를 FullCalendar의 Event 형식에 맞게 가공 후 전송
`stream()은 lambda 식과 비슷하게 변수를 뽑아서 가공할 메서드에 넣어주는 역할을 수행`
- stream()은 Java 컬렉션(예: List, Set)이나 배열의 요소를 하나 씩 처리하기 위한 파이프라인 생성 메서드

**Comment by jaekim3220** [comment]
# ~~TODO~~ 
~~Transaction을 사용해 환자가 예약 목록 `reservers` 데이터와 의사의 `vacations` 데이터를 SELECT해 JSON 형태로 변환해 FullCalendar로 보내되 하나라도 SELECT에 실패할 경우  Rollback되도록 상위 BO를 생성해 `reservers`, `vacations`의 DB SELECT 기능~~
=> 논리 오류

**Comment by jaekim3220** [comment]
# @Transactional 사용 시 주의
Transactional, try-catch, throw로 환자, 의사 데이터를 가져올 경우 데이터가 없으면 무조건 에러가 발생해서 논리에 부합하지 않음

**Comment by jaekim3220** [comment]
# vacations 데이터 INSERT 불가
!!!!! 500에러 !!!!!
`Field 'scheduleColor' doesn't have a default value] with root cause` => Mapper, XML, BO 확인

=> 해결 DB에서 'scheduleColor' column 삭제함.
