### ISSUE TITLE
고객 `예약 목록`, `예약 상세 페이지` SELECT, UPDATE API 구현

### ISSUE THREAD

**Issue by jaekim3220** [jaekim3220/backEndProject#7]
# TODO 
고객 `예약 목록`, `예약 상세 페이지` API 구현
- [ ] 고객 `예약 목록`
  - [x] Model과 Thymeleaf 문법을 사용해 `reservers` DB에서 로그인한 환자가 예약한 예약 내역을 화면에 추출
  - [x] `이전`, `다음` 버튼 기능 구현
  - [ ] (옵션)doctorNum을 사용해 진료 과목 추출

**Comment by jaekim3220** [comment]
# !!!!!500에러발생!!!!!

화면 : 
There was an unexpected error (type=Internal Server Error, status=500).
Name for argument of type [int] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag.
java.lang.IllegalArgumentException: Name for argument of type [int] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag.

Console : 
[2m2024-11-30T13:51:10.147+09:00[0;39m [31mERROR[0;39m [35m16992[0;39m [2m---[0;39m [2m[p-nio-80-exec-1][0;39m [2m[0;39m[36mo.a.c.c.C.[.[.[/].[dispatcherServlet]   [0;39m [2m:[0;39m Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalArgumentException: Name for argument of type [int] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag.] with root cause

java.lang.IllegalArgumentException: Name for argument of type [int] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag.

**Comment by jaekim3220** [comment]
# 에러 원인 파악
 '-parameters'  관련 문구를 통해  '-parameters' 가 500 에러 해결의 힌트라고 판단.
해당  '-parameters'  기능을 찾아볼 것

# 에러 원인 확인
@GetMapping("/reserve-list-view")의 페이징 기능에 사용될 parameter(page, size)는 정확히 URL에 삽입되었지만  메서드의 `Lombok이나 IDE에서 컴파일된 클래스 파일에 매개변수 이름 정보가 누락`되는 `리플렉션` 에러가 발생한 것이 원인.
## 해결 방법
메서드에서 Request하는 변수(Query Parameter)이름을 어노테이션(Annotation)에 명시적으로 지정해 해당 변수(Query Parameter)를 받아올 수 있도록 코드를 수정할 것.

※ 추신 : 컴파일 시점에 -parameters 옵션 적용 방법을 사용하지 않은 이유
- 김영한 님의 `인프런 스프링, JPA 강의 자주 하는 질문` p27 ~p30까지 해당 에러의 설명과 해결 방법이 매우 자세히 나와있음.
- 다만, IntelliJ IDEA로 설정하거나 사용할 경우에만 적용이 되기 때문에 사용하지 않을 것.

**Comment by jaekim3220** [comment]
# !!!!!500에러 해결!!!!!
메서드에서 Request하는 변수(Query Parameter)이름을 어노테이션(Annotation)에 명시적으로 지정해 IDE, 컴파일러, 또는 Request Parameter의 이름 불일치로 발생한 문제를 해결 및 방지 성공

**Comment by jaekim3220** [comment]
# !!!!!500에러 해결!!!!!
메서드에서 Request하는 변수(Query Parameter)이름을 어노테이션(Annotation)에 명시적으로 지정해 IDE, 컴파일러, 또는 Request Parameter의 이름 불일치로 발생한 문제를 해결 및 방지 성공
`결론 : 비필수 파라미터 형태로 파라미터 불러오기 실행`
